path: C:\Users\omerh\Desktop\new_tests  # dataset root dir

train: train/images  # train images (relative to 'path')
val: test/images  # val images (relative to 'path')
#test: test/images

transforms:
  rotate: 0.3  # Probability of rotation
  scale: 0.2   # Probability of scaling
  brightness: 0.2  # Probability of changing brightness
  contrast: 0.2    # Probability of changing contrast

names:
  0: Healthy
  1: Sick
